version: '3.3'
services:
  web:
    build: .
    working_dir: /app/server
    command: python server.py
    environment:
      - DATABASE_URI=postgresql://admin:admin@postgres:5432/sreality
    ports:
      - "8080:8080"
    depends_on:
      - db
  scrapy:
    build: .
    working_dir: /app/scraper
    command: scrapy crawl sreality_spider
    environment:
      - DATABASE_URI=postgresql://admin:admin@postgres:5432/sreality
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sreality
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
